version: '3'

services:

  redis:
    image: redis:alpine

  web:
    image: flaskapp
    build: ./web
    ports:
      - "5555:5555"
    volumes:
      - ./web:/code
#    environment:
#      FLASK_ENV: development
